import { MandalaSettings } from './mandala';

export interface PatternPreset {
  name: string;
  description: string;
  settings: Omit<MandalaSettings, 'seed'>;
}

export const PATTERN_PRESETS: PatternPreset[] = [
  {
    name: 'Classic Lotus',
    description: 'Traditional lotus flower mandala',
    settings: {
      patternType: 'lotus',
      segments: 8,
      rings: 5,
      radius: 300,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.6,
      detailDensity: 0.5,
      ornamentComplexity: 0.4,
      rotationOffset: 0,
      segmentOffset: false,
      spacingMultiplier: 1,
      centerScale: 1.2,
      strokeColor: '#ffffff',
      backgroundColor: '#0a0a0a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Intricate Mehndi',
    description: 'Detailed henna-inspired patterns',
    settings: {
      patternType: 'mehndi',
      segments: 16,
      rings: 8,
      radius: 350,
      lineWeight: 1.5,
      symmetry: true,
      petalCurvature: 0.7,
      detailDensity: 0.8,
      ornamentComplexity: 0.7,
      rotationOffset: 0,
      segmentOffset: true,
      spacingMultiplier: 0.9,
      centerScale: 0.8,
      strokeColor: '#ef4444',
      backgroundColor: '#1a0a0a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Geometric Temple',
    description: 'Clean architectural patterns',
    settings: {
      patternType: 'traditional',
      segments: 12,
      rings: 6,
      radius: 300,
      lineWeight: 2.5,
      symmetry: true,
      petalCurvature: 0.3,
      detailDensity: 0.3,
      ornamentComplexity: 0.4,
      rotationOffset: 15,
      segmentOffset: false,
      spacingMultiplier: 1.1,
      centerScale: 1,
      strokeColor: '#fbbf24',
      backgroundColor: '#000000',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Paisley Flow',
    description: 'Curved teardrop motifs',
    settings: {
      patternType: 'paisley',
      segments: 10,
      rings: 6,
      radius: 320,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.8,
      detailDensity: 0.6,
      ornamentComplexity: 0.5,
      rotationOffset: 0,
      segmentOffset: true,
      spacingMultiplier: 1,
      centerScale: 0.9,
      strokeColor: '#06b6d4',
      backgroundColor: '#0a1a1a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Rangoli Festival',
    description: 'Vibrant floor art patterns',
    settings: {
      patternType: 'rangoli',
      segments: 8,
      rings: 5,
      radius: 280,
      lineWeight: 3,
      symmetry: true,
      petalCurvature: 0.4,
      detailDensity: 0.5,
      ornamentComplexity: 0.8,
      rotationOffset: 22.5,
      segmentOffset: false,
      spacingMultiplier: 1.2,
      centerScale: 1.3,
      strokeColor: '#f97316',
      backgroundColor: '#1a1410',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Minimal Zen',
    description: 'Simple and meditative',
    settings: {
      patternType: 'traditional',
      segments: 6,
      rings: 4,
      radius: 250,
      lineWeight: 1.5,
      symmetry: true,
      petalCurvature: 0.5,
      detailDensity: 0.2,
      ornamentComplexity: 0.2,
      rotationOffset: 0,
      segmentOffset: false,
      spacingMultiplier: 1.3,
      centerScale: 1,
      strokeColor: '#ffffff',
      backgroundColor: '#0a0a0a',
      strokeOpacity: 0.8,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Dashed Outline',
    description: 'Geometric with dashed strokes',
    settings: {
      patternType: 'traditional',
      segments: 12,
      rings: 6,
      radius: 300,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.3,
      detailDensity: 0.4,
      ornamentComplexity: 0.3,
      rotationOffset: 0,
      segmentOffset: true,
      spacingMultiplier: 1,
      centerScale: 1,
      strokeColor: '#818cf8',
      backgroundColor: '#0f0f1a',
      strokeOpacity: 1,
      strokeDash: 'dashed',
    },
  },
  {
    name: 'Dense Ornament',
    description: 'Maximum detail and complexity',
    settings: {
      patternType: 'traditional',
      segments: 18,
      rings: 9,
      radius: 350,
      lineWeight: 1,
      symmetry: true,
      petalCurvature: 0.7,
      detailDensity: 1,
      ornamentComplexity: 1,
      rotationOffset: 0,
      segmentOffset: true,
      spacingMultiplier: 0.85,
      centerScale: 0.7,
      strokeColor: '#ffffff',
      backgroundColor: '#0a0a0a',
      strokeOpacity: 0.9,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Bold Lotus',
    description: 'Thick lines, high contrast',
    settings: {
      patternType: 'lotus',
      segments: 12,
      rings: 5,
      radius: 300,
      lineWeight: 4,
      symmetry: true,
      petalCurvature: 0.5,
      detailDensity: 0.4,
      ornamentComplexity: 0.3,
      rotationOffset: 0,
      segmentOffset: false,
      spacingMultiplier: 1.1,
      centerScale: 1.4,
      strokeColor: '#ffffff',
      backgroundColor: '#000000',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Ethereal Dotted',
    description: 'Light dotted pattern',
    settings: {
      patternType: 'traditional',
      segments: 12,
      rings: 7,
      radius: 320,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.6,
      detailDensity: 0.5,
      ornamentComplexity: 0.5,
      rotationOffset: 15,
      segmentOffset: false,
      spacingMultiplier: 1,
      centerScale: 1,
      strokeColor: '#ffffff',
      backgroundColor: '#0a0a0a',
      strokeOpacity: 0.7,
      strokeDash: 'dotted',
    },
  },
  {
    name: 'Peacock Splendor',
    description: 'Feather and eye motifs',
    settings: {
      patternType: 'peacock',
      segments: 8,
      rings: 4,
      radius: 320,
      lineWeight: 1.5,
      symmetry: true,
      petalCurvature: 0.6,
      detailDensity: 0.7,
      ornamentComplexity: 0.8,
      rotationOffset: 0,
      segmentOffset: false,
      spacingMultiplier: 1.3,
      centerScale: 0.8,
      strokeColor: '#14b8a6',
      backgroundColor: '#051a1a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Persian Garden',
    description: 'Authentic boteh paisley',
    settings: {
      patternType: 'paisley',
      segments: 12,
      rings: 6,
      radius: 300,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.7,
      detailDensity: 0.8,
      ornamentComplexity: 0.6,
      rotationOffset: 15,
      segmentOffset: true,
      spacingMultiplier: 1,
      centerScale: 0.9,
      strokeColor: '#10b981',
      backgroundColor: '#051a0a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Festival Diwali',
    description: 'Vibrant celebration colors',
    settings: {
      patternType: 'rangoli',
      segments: 8,
      rings: 6,
      radius: 300,
      lineWeight: 2.5,
      symmetry: true,
      petalCurvature: 0.5,
      detailDensity: 0.9,
      ornamentComplexity: 0.8,
      rotationOffset: 22.5,
      segmentOffset: false,
      spacingMultiplier: 1.1,
      centerScale: 1.3,
      strokeColor: '#facc15',
      backgroundColor: '#1a1a05',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
  {
    name: 'Lotus Enlightenment',
    description: 'Golden ratio petals',
    settings: {
      patternType: 'lotus',
      segments: 13,
      rings: 5,
      radius: 300,
      lineWeight: 2,
      symmetry: true,
      petalCurvature: 0.618,
      detailDensity: 0.6,
      ornamentComplexity: 0.5,
      rotationOffset: 0,
      segmentOffset: false,
      spacingMultiplier: 1.05,
      centerScale: 1.1,
      strokeColor: '#f472b6',
      backgroundColor: '#1a051a',
      strokeOpacity: 1,
      strokeDash: 'solid',
    },
  },
];
